# This is a Tree Regression code!

In [2]:
#CART
from numpy import *
import TreeRegres
testMat = mat(eye(4))
#print testMat
mat0, mat1 = TreeRegres.binSplitDataSet(testMat,1,0.5)
print mat0
print mat1

[[ 0.  1.  0.  0.]]
[[ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [3]:
reload(TreeRegres)
from numpy import *
myDat = TreeRegres.loadDataSet('ex2.txt')
print shape(myDat)
myMat = mat(myDat)
TreeRegres.createTree(myMat)

(200, 2)


{'left': {'left': {'left': {'left': 105.24862350000001,
    'right': 112.42895575000001,
    'spInd': 0,
    'spVal': 0.958512},
   'right': {'left': {'left': {'left': {'left': 87.310387500000004,
       'right': {'left': {'left': 96.452866999999998,
         'right': {'left': 104.82540899999999,
          'right': {'left': 95.181792999999999,
           'right': 102.25234449999999,
           'spInd': 0,
           'spVal': 0.872883},
          'spInd': 0,
          'spVal': 0.892999},
         'spInd': 0,
         'spVal': 0.910975},
        'right': 95.275843166666661,
        'spInd': 0,
        'spVal': 0.85497},
       'spInd': 0,
       'spVal': 0.944221},
      'right': {'left': 81.110151999999999,
       'right': 88.784498800000009,
       'spInd': 0,
       'spVal': 0.811602},
      'spInd': 0,
      'spVal': 0.833026},
     'right': 102.35780185714285,
     'spInd': 0,
     'spVal': 0.790312},
    'right': 78.085643250000004,
    'spInd': 0,
    'spVal': 0.759504},
   'spInd

In [4]:
#后剪枝
reload(TreeRegres)
myTree = TreeRegres.createTree(myMat, ops=(0,1))
myDatTest = TreeRegres.loadDataSet('ex2test.txt')
myMatTest = mat(myDatTest)
TreeRegres.prune(myTree, myMatTest)

merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging
merging


{'left': {'left': {'left': {'left': 92.523991499999994,
    'right': {'left': {'left': {'left': 112.386764,
       'right': 123.559747,
       'spInd': 0,
       'spVal': 0.960398},
      'right': 135.83701300000001,
      'spInd': 0,
      'spVal': 0.958512},
     'right': 111.2013225,
     'spInd': 0,
     'spVal': 0.956951},
    'spInd': 0,
    'spVal': 0.965969},
   'right': {'left': {'left': {'left': {'left': {'left': {'left': {'left': {'left': {'left': {'left': {'left': 96.41885225,
              'right': 69.318648999999994,
              'spInd': 0,
              'spVal': 0.948822},
             'right': {'left': {'left': 110.03503850000001,
               'right': {'left': 65.548417999999998,
                'right': {'left': 115.75399400000001,
                 'right': {'left': {'left': 94.396114499999996,
                   'right': 85.005351000000005,
                   'spInd': 0,
                   'spVal': 0.912161},
                  'right': {'left': {'left': 106.81466

In [7]:
#树模型
reload (TreeRegres)
myMat2 = mat(TreeRegres.loadDataSet('exp2.txt'))
TreeRegres.createTree(myMat2, TreeRegres.modelLeaf, TreeRegres.modelErr, (1,10))

{'left': matrix([[  1.69855694e-03],
         [  1.19647739e+01]]), 'right': matrix([[ 3.46877936],
         [ 1.18521743]]), 'spInd': 0, 'spVal': 0.285477}

In [8]:
#contrast with Regression Tree
reload (TreeRegres)
trainMat = mat(TreeRegres.loadDataSet('bikeSpeedVsIq_train.txt'))
testMat = mat(TreeRegres.loadDataSet('bikeSpeedVsIq_test.txt'))
myTree = TreeRegres.createTree(trainMat, ops=(1,20))
yHat = TreeRegres.createForeCast(myTree, testMat[:,0])
corrcoef(yHat,testMat[:,1],rowvar=0)[0,1]

0.96408523182221406

In [9]:
#contrast with Model Tree
#reload (TreeRegres)
myTree = TreeRegres.createTree(trainMat,TreeRegres.modelLeaf,TreeRegres.modelErr,(1,20))
yHat = TreeRegres.createForeCast(myTree,testMat[:,0],TreeRegres.modelTreeEval)
corrcoef(yHat,testMat[:,1],rowvar=0)[0,1]

0.97604121913806374

In [11]:
#contrast with Standard Linear Regression
ws, X, Y = TreeRegres.linearSolve(trainMat)

for i in range(shape(testMat)[0]):
    yHat[i] = testMat[i,0]*ws[1,0]+ws[0,0]

corrcoef(yHat,testMat[:,1],rowvar=0)[0,1]

0.94346842356747584

In [17]:
#GUI by Tkinter
from Tkinter import *
root=Tk()
myLabel = Label(root,text='hello world!')
myLabel.grid()
root.mainloop()