# This is a SVD code!

In [5]:
#test for SVD in linalg
from numpy import *
U, Sigma, VT = linalg.svd([[1,1],[7,7]])
print 'U: ',U
print 'Sigma: ',Sigma
print 'VT: ',VT

U:  [[-0.14142136 -0.98994949]
 [-0.98994949  0.14142136]]
Sigma:  [ 10.   0.]
VT:  [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [6]:
import SVD
Data = SVD.loadExData()
U, Sigma, VT = linalg.svd(Data)
#print 'U: ',U
print 'Sigma: ',Sigma
#print 'VT: ',VT

Sigma:  [  9.64365076e+00   5.29150262e+00   8.36478329e-16   6.91811207e-17
   1.11917251e-33]


In [10]:
Sig3 = mat([[Sigma[0],0],[0,Sigma[1]]])
U[:,:2]*Sig3*VT[:2,:]

matrix([[ -6.97395509e-16,   3.48697754e-16,   3.48697754e-16,
           2.00000000e+00,   2.00000000e+00],
        [ -1.04609326e-15,   5.23046632e-16,   5.23046632e-16,
           3.00000000e+00,   3.00000000e+00],
        [ -3.48697754e-16,   1.74348877e-16,   1.74348877e-16,
           1.00000000e+00,   1.00000000e+00],
        [  1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
           5.19259273e-17,   5.19259273e-17],
        [  2.00000000e+00,   2.00000000e+00,   2.00000000e+00,
           1.03851855e-16,   1.03851855e-16],
        [  5.00000000e+00,   5.00000000e+00,   5.00000000e+00,
           0.00000000e+00,   0.00000000e+00],
        [  1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
           5.19259273e-17,   5.19259273e-17]])

In [13]:
#calculate the similarity
reload (SVD)
myMat = mat(SVD.loadExData())
print SVD.ecludSim(myMat[:,0],myMat[:,4])
print SVD.ecludSim(myMat[:,0],myMat[:,0])
print SVD.cosSim(myMat[:,0],myMat[:,4])
print SVD.cosSim(myMat[:,0],myMat[:,0])
print SVD.pearsSim(myMat[:,0],myMat[:,4])
print SVD.pearsSim(myMat[:,0],myMat[:,0])

0.129731907557
1.0
0.5
1.0
0.205965381738
1.0


In [14]:
reload (SVD)
myMat = mat(SVD.loadExData())
myMat[0,1]=myMat[0,0]=myMat[1,0]=myMat[2,0]=4
myMat[3,3]=2
print myMat

[[4 4 0 2 2]
 [4 0 0 3 3]
 [4 0 0 1 1]
 [1 1 1 2 0]
 [2 2 2 0 0]
 [5 5 5 0 0]
 [1 1 1 0 0]]


In [15]:
SVD.recommend(myMat,2)

the 1 and 0 similarity is: 1.000000
the 1 and 3 similarity is: 0.928746
the 1 and 4 similarity is: 1.000000
the 2 and 0 similarity is: 1.000000
the 2 and 3 similarity is: 1.000000
the 2 and 4 similarity is: 0.000000


[(2, 2.5), (1, 2.0243290220056256)]

In [18]:
SVD.recommend(myMat,2,simMeas=SVD.pearsSim)

the 1 and 0 similarity is: 1.000000
the 1 and 3 similarity is: 1.000000
the 1 and 4 similarity is: 1.000000
the 2 and 0 similarity is: 1.000000
the 2 and 3 similarity is: 1.000000
the 2 and 4 similarity is: 0.000000


[(2, 2.5), (1, 2.0)]

In [19]:
#recommend system
from numpy import linalg as la
U,Sigma,VT=la.svd(mat(SVD.loadExData2()))
print Sigma

[ 15.77075346  11.40670395  11.03044558   4.84639758   3.09292055
   2.58097379   1.00413543   0.72817072   0.43800353   0.22082113
   0.07367823]


In [21]:
Sig2=Sigma**2
print sum(Sig2)
print sum(Sig2)*0.9
print sum(Sig2[:2])
print sum(Sig2[:3])

542.0
487.8
378.829559511
500.500289128


In [22]:
reload (SVD)
SVD.recommend(myMat,1,estMethod=SVD.svdEst)

the 1 and 0 similarity is: 0.498142
the 1 and 3 similarity is: 0.498131
the 1 and 4 similarity is: 0.509974
the 2 and 0 similarity is: 0.552670
the 2 and 3 similarity is: 0.552976
the 2 and 4 similarity is: 0.217301


[(2, 3.4177569186592387), (1, 3.3307171545585641)]

In [23]:
SVD.recommend(myMat,1,estMethod=SVD.svdEst,simMeas=SVD.pearsSim)

the 1 and 0 similarity is: 0.626075
the 1 and 3 similarity is: 0.672793
the 1 and 4 similarity is: 0.614375
the 2 and 0 similarity is: 0.429334
the 2 and 3 similarity is: 0.387057
the 2 and 4 similarity is: 0.043539


[(2, 3.4992661245386789), (1, 3.3272324280613659)]

In [24]:
#example for image compress
reload (SVD)
SVD.imgCompress(2)

****original matrix******
0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 